### PR TITLE
Update to `hub` 2.2.0

### PR DESCRIPTION
**Pull request by jingweno**

### CODE REVIEW

**Comment by mislav** [comment]
Why do we keep maintaining this separate formula? Why don't we just use "hub" from Homebrew? /cc @mikemcquaid

**Comment by tarebyte** [comment]
@mislav are there any extra dependencies that are needed if we use the Homebrew formula? If not there we could probably make the switch.

**Comment by jingweno** [comment]
To my knowledge, Homebrew bottles don't work with Boxen (at least last time I tried). If we were to go with the official `hub` formula, the only option is to build it from source (related discussion, https://github.com/boxen/puppet-hub/pull/10#issuecomment-68600179).

The solution here is to replace "url" with the precompiled package:

```
url "https://github.com/github/hub/releases/download/v2.2.0/hub-mac-amd64-2.2.0.tar.gz"
```

instead of from the Homebrew formula:

```
url "https://github.com/github/hub/archive/v2.2.0.tar.gz"
```

**Comment by mislav** [comment]
Ah, got it.

**Comment by mikemcquaid** [comment]
> To my knowledge, Homebrew bottles don't work with Boxen (at least last time I tried). If we were to go with the official hub formula, the only option is to build it from source (related discussion, #10 (comment)).

They do if they are either installed to `/usr/local` or `cellar :any`.

**Comment by jingweno** [comment]
@mikemcquaid Any pointer to get it to work with Boxen?

**Comment by mikemcquaid** [comment]
@jingweno I think we talked about this in Homebrew before: the best bet is to try and work out how to remove the references to the Cellar embedded into the binaries. For example, run `brew install hub` in `/usr/local` and then `brew bottle -v hub` and you'll see:

```
...
==> Detecting if hub-2.2.0.yosemite.bottle.1.tar.gz is relocatable...
Warning: String '/usr/local/Cellar' still exists in these files:
/usr/local/Cellar/hub/2.2.0/bin/hub
 --> match '/usr/local/Cellar/go/1.4.1/libexec' at offset 0x4cbf30
 --> match '/usr/local/Cellar/go/1.4.1/libexec/src/compress/bzip2/move_to_front.go' at offset 0x65f979
 --> match '/usr/local/Cellar/go/1.4.1/libexec/src/compress/bzip2/huffman.go' at offset 0x65f9c1
 --> match '/usr/local/Cellar/go/1.4.1/libexec/src/compress/bzip2/bzip2.go' at offset 0x65fa03
 --> match '/usr/local/Cellar/go/1.4.1/libexec/src/compress/bzip2/bit_reader.go' at offset 0x65fa43
 --> match '/usr/local/Cellar/go/1.4.1/libexec/src/crypto/dsa/dsa.go' at offset 0x65fa88
...
```

If we can get rid of these references somehow we can generate a bottle that's usable anywhere. I don't know enough about Go to help here, unfortunately.

**Comment by jingweno** [comment]
@mikemcquaid Now I remember the conversation. `hub` doesn't rely on the Go compiler to run. The binary bundles the Go runtime - the dependencies from the output of `brew bottle` are in the built binary. `brew bottle` seems to use [`strings` to print out/check dependencies of a binary]((https://github.com/Homebrew/homebrew/blob/master/Library/Homebrew/cmd/bottle.rb#L66-L79). It may not work for Go.

**Comment by mikemcquaid** [comment]
It does, yep. The question is: why is Go storing those strings there? Things still appear to work, I agree, but I wouldn't be happy making e.g. a general exception for Go programs without knowing what's going on here. At a guess these are stored for e.g. debug symbols or backtraces in which case they should somehow be strippable/relocatable.

**Comment by jingweno** [comment]
@mikemcquaid Good question. I'm curious about that too. Yup, they could be used for pinpoint source in debug or stacktraces. I've asked the question in the Go mailing list [here](https://groups.google.com/forum/#!topic/golang-nuts/Zt7zGB2Q2Wo). Let's see what answers we'll get.

**Comment by jingweno** [comment]
> I wouldn't be happy making e.g. a general exception for Go programs without knowing what's going on here.

It sounds like the approach of using `strings` works for all binaries except Go's. Confirmed from the [mailing list](https://groups.google.com/forum/#!topic/golang-nuts/Zt7zGB2Q2Wo), the source paths are used in stacktrace. Maybe could skip this dependencies check for a Go program?

**Comment by mikemcquaid** [comment]
Sure; my point is that the stacktraces will then be incorrect if they have those paths embedded in them. I'd be surprised if there's no way of telling Go to not include these paths.

**Comment by mikemcquaid** [comment]
So, from doing some reading it seems it's not currently possible. I am interested in trying to workaround this but that solution won't be skip this checking for all Go programs.

**Comment by mikemcquaid** [comment]
Possible solutions I need to investigate
- stripping the output binary
- temporarily copying the Go `prefix` to the `buildpath` and seeing if that can coax it to changing the hardcoded strings

**Comment by mikemcquaid** [comment]
Ah, life's too short. Made a PR to ignore these selectively here: https://github.com/Homebrew/homebrew/pull/36894

Works with `hub` and once we've merged it (or something similar) we'll be able to have a `cellar :any` `hub` formula so can rely on that instead.

**Comment by jingweno** [comment]
> Made a PR to ignore these selectively here: Homebrew/homebrew#36894

Nice, thanks! :+1:

**Comment by mikemcquaid** [comment]
That PR was merged and I've updated the Homebrew bottle to be `cellar :any`.

**Comment by jingweno** [comment]
@mikemcquaid Sweet, see https://github.com/boxen/puppet-hub/pull/12

**Pull request merged**
