### PR TITLE
Use official Homebrew `hub` formula

### PR DESCRIPTION
**Pull request by jingweno**
Homebrew now supports [installing bottles anywhere for Go apps](https://github.com/Homebrew/homebrew/pull/36894).
We can remove the previous hack and reuse the `hub` formula from Homebrew

/cc @mislav @mikemcquaid

### CODE REVIEW

**Comment by mikemcquaid** [comment]
Up to you but I wonder if it's worth still keeping this formula in here but making it a copy of the Homebrew formula. This means that Boxen admins can choose when to up date their hub rather than having it be defined by Homebrew. I don't mind either way, though!

**Comment by jingweno** [comment]
I personally prefer users to always use the latest hub so that we'd get immediate feedback. @mislav What do you think?

**Comment by mikemcquaid** [comment]
I personally agree but the problem with that is then the Puppet module version no longer controls the version of Hub that's installed (which would be inconsistent with other modules).

**Comment by mislav** [comment]
The solution I would be happy with is Homebrew allowing us to pick a version when installing a package. Then this puppet module could continue locking down the version while at the same time reusing the main Homebrew formula.

How hard would it be to add such a feature to Homebrew?

**Comment by mikemcquaid** [comment]
Pretty hard and we'd be unlikely to include it due to the increased support burden. The approach for picking versions is basically: vendor older versions or add them to the `homebrew-versions` to support them.

**Comment by mislav** [comment]
I'm torn. On one hand I feel like it's in order that if you used boxen and you haven't touched any configs, your software versions should be frozen in time. On the other hand, that means that if you never bump puppet-hub in your boxen, you never get any of our bug fixes.

I feel like hub version should be frozen, because otherwise it would upgrade boxen users to hub 2.3 when it comes out and that's definitely what we don't want.

**Comment by mikemcquaid** [comment]
> I'm torn. On one hand I feel like it's in order that if you used boxen and you haven't touched any configs, your software versions should be frozen in time. On the other hand, that means that if you never bump puppet-hub in your boxen, you never get any of our bug fixes.

I feel your pain here, I totally agree but it seems to be a design decision of Boxen to do so.

**Comment by mislav** [comment]
OK so let's punt on this PR and keep things as before, @jingweno.

**Comment by jingweno** [comment]
Alright, I'm convinced it's a good idea to freeze hub version in boxen. Do we still want to port [the official hub formula](https://github.com/Homebrew/homebrew/blob/master/Library/Formula/hub.rb) over? With @mikemcquaid's earlier fix, bottles should work for Boxen now and we wouldn't need the current hack.

**Comment by mikemcquaid** [comment]
Yeh, probably worth still porting the formula over I think :+1:

**Comment by mislav** [comment]
I don't feel that the current formula is hacky, but if you want consistency then sure, port the formula over. So if we did that, would the precompiled bottles that Homebrew hosts still be reused even if it's a custom formula?

**Comment by mikemcquaid** [comment]
> I don't feel that the current formula is hacky, but if you want consistency then sure, port the formula over. So if we did that, would the precompiled bottles that Homebrew hosts still be reused even if it's a custom formula?

As long as the version is kept the same (e.g. no trailing `-boxen1`) and the bottle block as left unchanged: yes.

**Comment by jingweno** [comment]
Closing in favor of https://github.com/boxen/puppet-hub/pull/13

**Pull request closed without merging**
