### PR TITLE
Update hub 2.2.3

### PR DESCRIPTION
**Pull request by n0ts**

### CODE REVIEW

**Comment by orien** [comment]
+1 yes please

**Comment by jacobbednarz** [comment]
Thanks! 🍭

**Comment by n0ts** [comment]
@jacobbednarz Thanks for merge. Could you set a git tag?

**Comment by jacobbednarz** [comment]
Cheers for the shove on this one. I only just released I didn't push this out 😛  It's available as [1.4.3](https://github.com/boxen/puppet-hub/releases/tag/1.4.3)

**Comment by orien** [comment]
Thanks @jacobbednarz and @n0ts

**Pull request merged**
